class UserError(Exception):
    """Exceptions raised by the bot due to user error."""

    pass
